# Move the directory to the second line
format = '$all$directory$character'
add_newline = false
command_timeout = 2000

[username]
style_user = "bold dimmed blue"

# configure directory
[directory]
truncation_length = 20
truncate_to_repo = false # don't truncate path
style = "bold italic #87A752"

[cmd_duration]
min_time = 4000
format = "Â· [$duration]($style) "
show_milliseconds = false
disabled = false
style = "italic #87A752"

[aws]
disabled = true

# [nodejs]
# disabled = true

[rust]
disabled = true

[status]
disabled = false
format = "[$status $common_meaning]($style) "

[gcloud]
disabled = true
